[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]]
repo = 'dcharbon/vim-flatbuffers'
on_ft = 'fbs'

[[plugins]]
repo = 'lark-parser/vim-lark-syntax'
on_ft = 'lark'

[[plugins]]
repo = 'Shougo/dein.vim'
